/**
 * services/supabaseService.js
 * Week 4 — Supabase persistence layer.
 * Replaces the in-memory scan store from Week 3.
 *
 * Tables required (run supabase-schema.sql in your Supabase SQL editor):
 *   scans      — one row per scan
 *   findings   — one row per finding, foreign key to scans.id
 *   reviews    — community reviews submitted on the homepage
 */

const { createClient } = require("@supabase/supabase-js");

// Initialise once. These come from backend/.env
const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY
);

/**
 * createScan
 * Inserts an initial scan record with status "running".
 * Called immediately when the POST /api/scan request arrives.
 *
 * @param {string} scanId   - UUID generated by the route
 * @param {string} owner    - GitHub repo owner
 * @param {string} repo     - GitHub repo name
 * @returns {Promise<Object>} the inserted row
 */
async function createScan(scanId, owner, repo) {
  const { data, error } = await supabase
    .from("scans")
    .insert({
      id: scanId,
      owner,
      repo,
      repo_url: `https://github.com/${owner}/${repo}`,
      status: "running",
      created_at: new Date().toISOString(),
    })
    .select()
    .single();

  if (error) {
    console.error("[supabaseService] createScan error:", error.message);
    throw error;
  }
  return data;
}

/**
 * saveFindings
 * Updates the scan record with summary data and status "complete",
 * then inserts all findings linked to that scan.
 *
 * @param {string} scanId
 * @param {Object} results - the full results object from scanOrchestrator.runAll
 */
async function saveFindings(scanId, results) {
  // 1. Update the scan row to complete
  const { error: scanError } = await supabase
    .from("scans")
    .update({
      status: "complete",
      completed_at: new Date().toISOString(),
      total_files: results.summary?.totalFiles ?? 0,
      total_commits: results.summary?.totalCommits ?? 0,
      findings_count: results.summary?.findingsCount ?? 0,
      file_tree: results.fileTree ?? [],
      recent_commits: results.recentCommits ?? [],
    })
    .eq("id", scanId);

  if (scanError) {
    console.error("[supabaseService] update scan error:", scanError.message);
    throw scanError;
  }

  // 2. Insert findings
  if (results.findings && results.findings.length > 0) {
    const rows = results.findings.map((f) => ({
      scan_id: scanId,
      category: f.category,
      severity: f.severity,
      message: f.message,
      detail: f.detail ?? null,
      tdd_ratio: f.tddRatio ?? null,
      file_path: f.file_path ?? null,
      line_number: f.line_number ?? null,
      metadata: f.structuralSignal ?? null,
    }));

    const { error: findingsError } = await supabase
      .from("findings")
      .insert(rows);

    if (findingsError) {
      console.error("[supabaseService] insert findings error:", findingsError.message);
      throw findingsError;
    }
  }

  console.log(`[supabaseService] saved ${results.findings?.length ?? 0} findings for ${scanId}`);
}

/**
 * getScanById
 * Fetches a scan and all its findings by scan ID.
 * Returns null if not found.
 *
 * @param {string} scanId
 * @returns {Promise<Object|null>}
 */
async function getScanById(scanId) {
  const { data: scan, error: scanError } = await supabase
    .from("scans")
    .select("*")
    .eq("id", scanId)
    .single();

  if (scanError) {
    if (scanError.code === "PGRST116") return null; // not found
    console.error("[supabaseService] getScanById error:", scanError.message);
    throw scanError;
  }

  const { data: findings, error: findingsError } = await supabase
    .from("findings")
    .select("*")
    .eq("scan_id", scanId)
    .order("created_at", { ascending: true });

  if (findingsError) {
    console.error("[supabaseService] get findings error:", findingsError.message);
    throw findingsError;
  }

  return {
    scanId: scan.id,
    status: scan.status,
    repoUrl: scan.repo_url,
    owner: scan.owner,
    repo: scan.repo,
    createdAt: scan.created_at,
    completedAt: scan.completed_at,
    summary: {
      totalFiles: scan.total_files,
      totalCommits: scan.total_commits,
      findingsCount: scan.findings_count,
    },
    findings: findings.map((f) => ({
      category: f.category,
      severity: f.severity,
      message: f.message,
      detail: f.detail,
      tddRatio: f.tdd_ratio,
      file_path: f.file_path,
      line_number: f.line_number,
      structuralSignal: f.metadata,
    })),
    fileTree: scan.file_tree ?? [],
    recentCommits: scan.recent_commits ?? [],
  };
}

/**
 * saveReview
 * Saves a community review submitted on the homepage.
 *
 * @param {Object} review - { name, role, stars, text }
 */
async function saveReview(review) {
  const { data, error } = await supabase
    .from("reviews")
    .insert({
      name: review.name,
      role: review.role ?? null,
      stars: review.stars,
      text: review.text,
      approved: false, // requires moderation before showing publicly
      created_at: new Date().toISOString(),
    })
    .select()
    .single();

  if (error) {
    console.error("[supabaseService] saveReview error:", error.message);
    throw error;
  }
  return data;
}

/**
 * getApprovedReviews
 * Returns all reviews that have been approved for public display.
 */
async function getApprovedReviews() {
  const { data, error } = await supabase
    .from("reviews")
    .select("id, name, role, stars, text, created_at")
    .eq("approved", true)
    .order("created_at", { ascending: false })
    .limit(20);

  if (error) {
    console.error("[supabaseService] getApprovedReviews error:", error.message);
    throw error;
  }
  return data;
}

module.exports = {
  createScan,
  saveFindings,
  getScanById,
  saveReview,
  getApprovedReviews,
};